### ISSUE TITLE
Finales Review/Abgabe-Checklist

### ISSUE THREAD

**Issue by carstenhag** [NiklasPor/App-Suite-Mosbach#3]
- [x] Alle TODOs im Text durchgegangen und gelöst
- [x] Überprüft, ob alle Aussagen eine Quelle haben
- [x] Überprüft, dass alle Quellen Datum/Autor haben
- [x] Überprüf, dass das richtige Quellenformat gewählt ist (vgl. oder nicht)
- [x] Überprüf, dass überall Einleitungen bestehen und Sinn ergeben
- [x] Typesetting fertiggestellt, damit fast-leere Seiten etc vermieden werden

Am Ende:
- [ ] Arbeit gedruckt
- [ ] Arbeit gebunden
- [ ] Per Mail geschickt
- [ ] Zur DHBW Mosbach gebracht

**Comment by carstenhag** [comment]
EInleitungen -> meh passt scho
